import type { SavedDiagram } from "../../domain"

export type RelatoPattern = {
  id: string
  name: string
  /** Title that `createDiagram` will give the generated diagram. */
  diagramTitle: string
  description: string
  createDiagram(now: string): SavedDiagram
}

// ─── Pattern definitions ──────────────────────────────────────────────────────

export const RELATO_PATTERNS: RelatoPattern[] = [
  {
    id: "blank",
    name: "Blank diagram",
    diagramTitle: "Untitled diagram",
    description: "Start from an empty architecture diagram.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Untitled diagram",
        description: "",
        nodes: [],
        edges: [],
        createdAt: now,
        updatedAt: now,
      }
    },
  },
  {
    id: "observer",
    name: "Observer",
    diagramTitle: "Observer pattern",
    description:
      "Define a one-to-many dependency so that when one object changes state, all its dependents are notified automatically.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Observer pattern",
        description: "Publisher, subscriber, and notification strategy.",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-publisher" as never,
            kind: "class",
            position: { x: 20, y: 40 },
            name: "Publisher[T any]",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: [
              "+ GetData() T",
              "+ Subscribe(Observer[T])",
              "+ Notify()",
            ],
            color: "oklch(0.62 0.24 28)",
          },
          {
            id: "node-engine" as never,
            kind: "class",
            position: { x: 20, y: 280 },
            name: "Engine[T any]",
            stereotype: null,
            role: "Subject",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- observers: Observer[]", "- fetcher: func() T"],
            methods: [
              "+ GetData() T",
              "+ Subscribe(Observer[T])",
              "+ notify()",
            ],
            color: "oklch(0.62 0.24 28)",
          },
          {
            id: "node-observer" as never,
            kind: "class",
            position: { x: 430, y: 190 },
            name: "Observer[T any]",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ Update(data T[])"],
            color: "oklch(0.76 0.16 85)",
          },
          {
            id: "node-subscriber" as never,
            kind: "class",
            position: { x: 760, y: 50 },
            name: "Subscriber",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- Strategies: NotificationStrategy[]"],
            methods: ["+ Update(data T[])"],
            color: "oklch(0.62 0.19 255)",
          },
          {
            id: "node-strategy" as never,
            kind: "class",
            position: { x: 980, y: 210 },
            name: "NotificationStrategy",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ Send(message)"],
            color: "oklch(0.72 0.19 149)",
          },
          {
            id: "node-sms" as never,
            kind: "class",
            position: { x: 760, y: 480 },
            name: "SmsStrategy",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ Send(message)"],
            color: "oklch(0.72 0.19 149)",
          },
          {
            id: "node-sse" as never,
            kind: "class",
            position: { x: 980, y: 480 },
            name: "SSE",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- manager: ClientManager"],
            methods: ["+ Send(message)"],
            color: "oklch(0.72 0.19 149)",
          },
          {
            id: "node-email" as never,
            kind: "class",
            position: { x: 1200, y: 480 },
            name: "EmailStrategy",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ Send(message)"],
            color: "oklch(0.72 0.19 149)",
          },
          {
            id: "node-client-manager" as never,
            kind: "class",
            position: { x: 980, y: 690 },
            name: "ClientManager",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- clients: map[string]chan string"],
            methods: [
              "+ AddClient(string)",
              "+ RemoveClient(string)",
              "+ Broadcast(string)",
            ],
            color: "oklch(0.72 0.19 149)",
          },
        ],
        edges: [
          {
            id: "edge-engine-publisher" as never,
            source: "node-engine" as never,
            target: "node-publisher" as never,
            sourceHandle: "top",
            targetHandle: "target-bottom",
            kind: "inheritance",
            label: "implements",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-engine-observer" as never,
            source: "node-engine" as never,
            target: "node-observer" as never,
            sourceHandle: "right",
            targetHandle: "target-left",
            kind: "aggregation",
            label: "has",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-subscriber-observer" as never,
            source: "node-subscriber" as never,
            target: "node-observer" as never,
            sourceHandle: "left",
            targetHandle: "target-right",
            kind: "inheritance",
            label: "implements",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-subscriber-strategy" as never,
            source: "node-subscriber" as never,
            target: "node-strategy" as never,
            sourceHandle: "right",
            targetHandle: "target-top",
            kind: "aggregation",
            label: "has",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-sms-strategy" as never,
            source: "node-sms" as never,
            target: "node-strategy" as never,
            sourceHandle: "top",
            targetHandle: "target-bottom",
            kind: "inheritance",
            label: "implements",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-sse-strategy" as never,
            source: "node-sse" as never,
            target: "node-strategy" as never,
            sourceHandle: "top",
            targetHandle: "target-bottom",
            kind: "inheritance",
            label: "implements",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-email-strategy" as never,
            source: "node-email" as never,
            target: "node-strategy" as never,
            sourceHandle: "top",
            targetHandle: "target-bottom",
            kind: "inheritance",
            label: "implements",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-sse-client-manager" as never,
            source: "node-sse" as never,
            target: "node-client-manager" as never,
            sourceHandle: "bottom",
            targetHandle: "target-top",
            kind: "aggregation",
            label: "has",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
        ],
      }
    },
  },
  {
    id: "memento",
    name: "Memento",
    diagramTitle: "Memento pattern",
    description:
      "Capture and externalize an object's internal state without violating encapsulation, so the object can be restored to this state later.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Memento pattern",
        description: "Capture and restore object state.",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-originator" as never,
            kind: "class",
            position: { x: 0, y: 0 },
            name: "Originator",
            stereotype: null,
            role: "State owner",
            summary:
              "Produces snapshots of its internal state and knows how to restore them.",
            files: ["src/patterns/memento/originator.ts"],
            reviewNotes: "",
            fields: ["- state: string"],
            methods: ["+ save(): Memento", "+ restore(m: Memento): void"],
            color: null,
          },
          {
            id: "node-memento" as never,
            kind: "class",
            position: { x: 0, y: 260 },
            name: "Memento",
            stereotype: null,
            role: "Snapshot",
            summary:
              "Immutable value object that captures state without exposing mutation.",
            files: ["src/patterns/memento/memento.ts"],
            reviewNotes: "",
            fields: ["- state: string"],
            methods: ["- Memento(state: string)", "- getState(): string"],
            color: null,
          },
          {
            id: "node-caretaker" as never,
            kind: "class",
            position: { x: 340, y: 0 },
            name: "Caretaker",
            stereotype: null,
            role: "History manager",
            summary:
              "Controls when to store state and when to roll the originator back.",
            files: ["src/patterns/memento/caretaker.ts"],
            reviewNotes: "",
            fields: ["- originator: Originator", "- history: Memento[]"],
            methods: ["+ doSomething(): void", "+ undo(): void"],
            color: null,
          },
        ],
        edges: [
          {
            id: "edge-orig-mem" as never,
            source: "node-originator" as never,
            target: "node-memento" as never,
            kind: "dependency",
            label: "creates",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-care-mem" as never,
            source: "node-caretaker" as never,
            target: "node-memento" as never,
            kind: "aggregation",
            label: "stores",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
        ],
      }
    },
  },
  {
    id: "strategy",
    name: "Strategy",
    diagramTitle: "Strategy pattern",
    description:
      "Define a family of algorithms, encapsulate each one, and make them interchangeable.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Strategy pattern",
        description: "",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-ctx" as never,
            kind: "class",
            position: { x: 0, y: 0 },
            name: "Context",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- strategy: Strategy"],
            methods: ["+ setStrategy(s: Strategy)", "+ executeStrategy()"],
            color: null,
          },
          {
            id: "node-strategy" as never,
            kind: "class",
            position: { x: 0, y: 240 },
            name: "Strategy",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ algorithmInterface()"],
            color: null,
          },
          {
            id: "node-strat-a" as never,
            kind: "class",
            position: { x: -200, y: 440 },
            name: "ConcreteStrategyA",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ algorithmInterface()"],
            color: null,
          },
          {
            id: "node-strat-b" as never,
            kind: "class",
            position: { x: 200, y: 440 },
            name: "ConcreteStrategyB",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ algorithmInterface()"],
            color: null,
          },
        ],
        edges: [
          {
            id: "edge-ctx-strat" as never,
            source: "node-ctx" as never,
            target: "node-strategy" as never,
            kind: "aggregation",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-a-strat" as never,
            source: "node-strat-a" as never,
            target: "node-strategy" as never,
            kind: "inheritance",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-b-strat" as never,
            source: "node-strat-b" as never,
            target: "node-strategy" as never,
            kind: "inheritance",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
        ],
      }
    },
  },
  {
    id: "factory-method",
    name: "Factory Method",
    diagramTitle: "Factory Method pattern",
    description:
      "Define an interface for creating objects, but let subclasses decide which classes to instantiate.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Factory Method pattern",
        description: "",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-creator" as never,
            kind: "class",
            position: { x: -200, y: 0 },
            name: "Creator",
            stereotype: "abstract",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ someOperation()", "# factoryMethod(): Product"],
            color: null,
          },
          {
            id: "node-concrete-creator" as never,
            kind: "class",
            position: { x: -200, y: 220 },
            name: "ConcreteCreator",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["# factoryMethod(): ConcreteProduct"],
            color: null,
          },
          {
            id: "node-product" as never,
            kind: "class",
            position: { x: 200, y: 0 },
            name: "Product",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ operation()"],
            color: null,
          },
          {
            id: "node-concrete-product" as never,
            kind: "class",
            position: { x: 200, y: 220 },
            name: "ConcreteProduct",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ operation()"],
            color: null,
          },
        ],
        edges: [
          {
            id: "edge-cc-c" as never,
            source: "node-concrete-creator" as never,
            target: "node-creator" as never,
            kind: "inheritance",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-cp-p" as never,
            source: "node-concrete-product" as never,
            target: "node-product" as never,
            kind: "inheritance",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-c-p" as never,
            source: "node-creator" as never,
            target: "node-product" as never,
            kind: "dependency",
            label: "creates",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-cc-cp" as never,
            source: "node-concrete-creator" as never,
            target: "node-concrete-product" as never,
            kind: "dependency",
            label: "creates",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
        ],
      }
    },
  },
  {
    id: "singleton",
    name: "Singleton",
    diagramTitle: "Singleton pattern",
    description:
      "Ensure a class has only one instance and provide a global access point to it.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Singleton pattern",
        description: "",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-singleton" as never,
            kind: "class",
            position: { x: 0, y: 0 },
            name: "Singleton",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- instance: Singleton", "- data: string"],
            methods: [
              "- Singleton()",
              "+ getInstance(): Singleton",
              "+ someBusinessLogic()",
            ],
            color: null,
          },
        ],
        edges: [
          {
            id: "edge-singleton-self" as never,
            source: "node-singleton" as never,
            target: "node-singleton" as never,
            sourceHandle: "right",
            targetHandle: "target-top",
            kind: "dependency",
            label: "instance",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0.5,
          },
        ],
      }
    },
  },
  {
    id: "adapter",
    name: "Adapter",
    diagramTitle: "Adapter pattern",
    description:
      "Convert the interface of a class into another interface clients expect, letting otherwise incompatible classes work together.",
    createDiagram(now) {
      return {
        schemaVersion: 1,
        id: `diagram-${crypto.randomUUID()}` as SavedDiagram["id"],
        title: "Adapter pattern",
        description: "",
        createdAt: now,
        updatedAt: now,
        nodes: [
          {
            id: "node-client" as never,
            kind: "class",
            position: { x: -300, y: 0 },
            name: "Client",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ clientCode(target: Target)"],
            color: null,
          },
          {
            id: "node-target" as never,
            kind: "class",
            position: { x: 0, y: 0 },
            name: "Target",
            stereotype: "interface",
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ request(): string"],
            color: null,
          },
          {
            id: "node-adapter" as never,
            kind: "class",
            position: { x: 0, y: 220 },
            name: "Adapter",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: ["- adaptee: Adaptee"],
            methods: ["+ request(): string"],
            color: null,
          },
          {
            id: "node-adaptee" as never,
            kind: "class",
            position: { x: 320, y: 220 },
            name: "Adaptee",
            stereotype: null,
            role: "",
            summary: "",
            files: [],
            reviewNotes: "",
            fields: [],
            methods: ["+ specificRequest(): string"],
            color: null,
          },
        ],
        edges: [
          {
            id: "edge-client-target" as never,
            source: "node-client" as never,
            target: "node-target" as never,
            kind: "dependency",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-adapter-target" as never,
            source: "node-adapter" as never,
            target: "node-target" as never,
            kind: "inheritance",
            label: "",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
          {
            id: "edge-adapter-adaptee" as never,
            source: "node-adapter" as never,
            target: "node-adaptee" as never,
            kind: "aggregation",
            label: "wraps",
            sourceLabel: "",
            targetLabel: "",
            color: null,
            strokeWidth: 2,
            curvature: 0,
          },
        ],
      }
    },
  },
]

/** O(1) lookup by pattern id. */
export const RELATO_PATTERN_BY_ID = new Map(
  RELATO_PATTERNS.map((p) => [p.id, p])
)
